### ISSUE TITLE
Especificaciones SGE

### ISSUE THREAD

**Issue by miguelangelronda** [javmoreno-developer/WorkLog#1]
Hola! Falta por indicar cómo vais a integrar los requisitos del módulo de Sistemas de Gestión Empresarial.

**Comment by javmoreno-developer** [comment]
Buenas miguel angel ,en nuestro caso para hacer la app que nos ha pedido
Antonio hemos diseñado una api en fast api usando python ,no se si sera
suficiente,la subiremos al repo en breve

**Comment by miguelangelronda** [comment]
Hola Javi, por supuesto, Con indicarlo en el repo es suficiente. Saludos!
