### ISSUE TITLE
Acceso al informe en PowerBI

### ISSUE THREAD

**Issue by josedavid-quero** [javmoreno-developer/WorkLog#2]
En el documento no se indica ningún tipo de información que se vaya a visualizar en el informe ni cómo se va a acceder al mismo.

**Comment by javmoreno-developer** [comment]
Buenas jose david para power bi tendremos una apta en el Dashboard del
admin y en este pondremos la grafica embebida

**Comment by josedavid-quero** [comment]
Indicad que se subirá al repositorio del proyecto y también se publicará en Power BI, compartiéndolo con la dirección de correo educativa del profesor.
jquesan535@m.educaand.es <-- esto no lo pongáis en la documentación

**Comment by javmoreno-developer** [comment]
Buenas José David no nos ha quedado claro que tenemos que hacer y subir en
el repo para tu módulo,podrías explicarnos cuando puedas por favor

**Comment by josedavid-quero** [comment]
Buenos días, lo de embeber el informe en la aplicación va a ser un poco bastante complicado, así que lo que tenéis que hacer es:
- hacer el informe como lo hemos estado haciendo en clase, utilizando el .csv que generáis como fuente de información.
- subir el informe al repositorio.
- compartirlo conmigo utilizando la dirección que os he proporcionado para que yo pueda verlo también online.
